### ISSUE TITLE
Allow some repositories to be marked as "roots", so their absolute paths work

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-modulizer#128]
This is to allow applications, like PSK, to convert correctly. We'll probably need a special Analyzer URLResolver.

**Comment by justinfagnani** [comment]
@FredKSchott this is an old bug I had for this issue, and it prescribes a solution I'm not in favor of any more: designating some repos as roots. As we've talked I think it's better to just support relative and absolute paths in any project, which you're working on. If there's a better issue already, just close this one.

**Comment by FredKSchott** [comment]
👍
