### ISSUE TITLE
Add more third party library mappings to our dependency map

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-modulizer#133]
```
"accessibility-developer-tools" npm mapping not found
"async" npm mapping not found
"chai" npm mapping not found
"es6-promise" npm mapping not found
"lodash" npm mapping not found
"marked" npm mapping not found
"mocha" npm mapping not found
"prism" npm mapping not found
"sinonjs" npm mapping not found
"sinon-chai" npm mapping not found
"stacky" npm mapping not found
```

**Comment by stramel** [comment]
Would it make sense to also allow the user to pass in a dependency mapping? that extends the default set you guys are curating?

**Comment by aomarks** [comment]
I also ran into the following missing ones. I think many of these come from `<app-media>`:

google-apis
google-youtube
url
webrtc-adapter
imagecapture-polyfill
intl-messageformat
pouchdb
pouchdb-find
intl
moment

**Comment by FredKSchott** [comment]
Fixed for Polymer elements by https://github.com/Polymer/polymer-modulizer/pull/381 & [limiting the number of elements we convert](https://github.com/Polymer/polymer-modulizer/blob/master/docs/polymer-modulize-repos.txt).

Feel free to submit a PR to add to our `dependency-map.json` if you run into a new package that cannot convert.

Remember that these can be resolved manually as well!
