### ISSUE TITLE
Investigate es-git as an alternative to nodegit

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-modulizer#166]
Some users are having problems installing due to nodegit build errors. es-git would side-step those issues, but isn't as used or tested. Last I looked, js-git (which es-git is forked from) was missing a lot of functionality, but that might not matter for our needs.

https://github.com/mariusGundersen/es-git

**Comment by Granze** [comment]
I've tried different versions of node but there's no way to install polymer-modulizer on my mac due the nodegit problems.

**Comment by Protoss78** [comment]
If you are running on Ubuntu 16.04 you will need to install the following packages for a successful 'yarn install' command:
`sudo apt install libssl-dev libcurl4-openssl-dev
`

Still not sure if I have to worry about this message though:
```
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.

```

**Comment by justinfagnani** [comment]
Sorry about the problems. We'll try to address this asap. For the team working on this, we didn't hit these problems, so it was kind of new. I think we may be able to just shell out to `git` to do what we need.

**Comment by akc42** [comment]
Same issue for me on Debian Stable.  I also had to install libcurl4-openssl-dev (I assume that brought in libssl-dev as one of its dependancies because I didn't have to install it).  yarn install had to go through a long build process of nodegit.

In my main Polymer project where I have both nodejs server and polymer client I built a script using git to set up some environment variables.  I use some very simple code to run a couple of git commands 
see below.
These run well on debian linux (intel and raspberry pi), mac and windows.
```
  const path = require('path');
  const gitBranch = 'git rev-parse --abbrev-ref HEAD';
  const gitVersion = 'git describe --abbrev=0 --tags';
  const root = path.resolve(__dirname,'..');
  const fs = require('fs');
  const child = require('child_process');

  function doGitCmd(cmd) {
    return new Promise((resolve,reject) => {
      child.exec(cmd,{cwd: root}, (err,stdout,stderr) => {
        if (stderr) {
          reject(new Error(stderr));
          return;
        }
        resolve(stdout.trim());
      });
    });
  }
  function checkGit() {
    return new Promise((resolve,reject) => {
      fs.stat(path.resolve(root,'.git'),(err,stats) => {
        if (err) {
          reject(err);
          return;
        }
        if (stats.isDirectory()) {
          resolve();
        } else {
          reject(new Error('Not a Directory'));
        }
      });
    });
  }

```

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Comment by justinfagnani** [comment]
Not yet, sorry. We're still getting full back online from the summit

**Comment by daKmoR** [comment]
oh I seem to have the same problem... seem to can't get nodegit running...

and actually it's not used in the modulizer? it's included in 
https://www.npmjs.com/package/polymer-workspaces

but there is no (public) git repo for it?
https://github.com/Polymer/polymer-workspaces
does not exists...

**Comment by justinfagnani** [comment]
Superceded by #204

**Comment by FredKSchott** [comment]
This has been fixed on master (a few PRs ago), and will be pushed out in the next release. In the mean time you can check out this repo and compile from source (and `yarn link`/`npm link`). 

Also https://github.com/Polymer/polymer-workspaces should be public now
