### ISSUE TITLE
Import of marked.js in marked-element is wrong

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-modulizer#174]
See: https://github.com/PolymerElements/marked-element/blob/4f4bc53fa846202784d95d9db5de3b2df83b60fa/marked-import.js#L1

It needs one more ../ to get out of the `@polymer/` directory in npm.

**Comment by stramel** [comment]
A couple other things I noticed,

- It didn't add the `marked` dependency.
- It didn't add any of the devDependencies.

**Comment by stramel** [comment]
@rictic @FredKSchott I believe this is fixed. Running the current state of modulizer against `marked-element` which resulted in `import '../../marked/lib/marked.js';` which should work.

**Comment by stramel** [comment]
@FredKSchott The issue originally by @rictic is fixed with the latest version (`0.3.0`).

**Comment by FredKSchott** [comment]
Nice! Thanks for the ping

**Comment by TimvdLippe** [comment]
FYI for those coming across this issue: the modulizer output has been resolved, but the update of `marked-element` has not been published yet. Therefore, your demos will be broken until they are updated.
