### ISSUE TITLE
Write dev dependencies out into package.json

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-modulizer#176]
Currently we don't convert them

**Comment by TimvdLippe** [comment]
Moreover, the modulizer overwrites the current package.json. E.g. on Polymer the scripts and dependencies are gone.

**Comment by stramel** [comment]
@FredKSchott @justinfagnani  WRT merging the `package.json` file that may exist? Currently with `flat: true` this will create "resolution hell" if a node module exists in that chain.

**Comment by justinfagnani** [comment]
Yeah, this can be closed.
