### ISSUE TITLE
Add node_modules to gitignore file

### ISSUE THREAD

**Issue by stramel** [Polymer/polymer-modulizer#183]
We should probably update the `.gitignore` file to have `node_modules`

**Comment by jorgecasar** [comment]
And `*.lock` should be included too. I guess `yarn.lock` nor `package-lock.json` shouldn't be in the component locking the components versions is an app responsibility.

**Comment by web-padawan** [comment]
According tho this [blog post](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/), lockfiles should be committed.
