### ISSUE TITLE
Generate npm-compatible licenses in package.json

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-modulizer#185]
Sounds like the direct translation from bower.json is causing warnings in npm: https://github.com/PolymerElements/marked-element/pull/77

**Comment by justinfagnani** [comment]
I think we can change the license to "BSD-3-Clause". @azakus do you know?

**Comment by stramel** [comment]
I believe that is correct @justinfagnani

**Comment by azakus** [comment]
Yeah, SGTM
