### ISSUE TITLE
Resulting import statements uses JS reserved keywords

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer-modulizer#197]
For example:

```js
import * as async from '../../polymer/lib/utils/async.js';
```

Ref https://github.com/PolymerElements/app-layout/issues/511

cc @justinfagnani @bicknellr

**Comment by bicknellr** [comment]
`async` doesn't actually appear to be a [reserved word in the spec](https://tc39.github.io/ecma262/#sec-reserved-words), even though async functions are definitely in there. I just talked with Adam and he mentioned that `async` should be an acceptable identifier. I think this is a JSC bug.

**Comment by bicknellr** [comment]
/index.html
```
<script type="module">
import * as async from "./mod.js";
console.log(async.a, async.b);
</script>
```
/mod.js
```
export const a = 1234;
export const b = 5678;
```

**Comment by keanulee** [comment]
Repro: https://kindly-physician.glitch.me/

Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=176573

**Comment by jsilvermist** [comment]
Isn't this only not a reserved keyword until we have fully implemented async/await? eg:
```js
function getMeep() {
  return new Promise((resolve, reject) => {
    return 'meep';
  });
}

async function speak() {
  console.log(await getMeep());
}
```

**Comment by keanulee** [comment]
`async` is technically not reserved - see demos above. `async/await` has already shipped in Chrome, and `async` can be used as an id.

**Comment by daflair** [comment]
You are absolutely correct (It's not planned to be reserved at all):
https://tc39.github.io/ecma262/#sec-keywords

But take it from a practical standpoint, let's try to fix some code with two occurrences of async, one is a function and the other is not a reserved keyword, but is a keyword:

```
  function async() {…} 
  async () => {}
```

So while it is not a reserved keyword, it still might not be very friendly from a development standpoint.

I think there needs to be a bug report with WebKit (not sure how that works out nowadays).

But it would really help the polymer community gain traction to minimize such barriers across non-conforming platforms.

**Comment by rictic** [comment]
Yeah, I'd call using `async` as an identifier as unclear at best. We should avoid creating identifiers named after keywords, semi-keywords (like `async`, `yield`, `await`, etc), and important built in values (like `Element`, `window`, `global`, `self`)

**Comment by keanulee** [comment]
WebKit has fixed this issue (`async` can be used as an identifier) and is in Safari TP. Should this be closed then @rictic ?

**Comment by justinfagnani** [comment]
Seems ok to close to me, though depending on what versions of Safari contain this bug we may still have to avoid `async`.
