### ISSUE TITLE
modulizer is overwriting .js files

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-modulizer#200]
Given this project layout:

```
- iron-test-helpers/
  - test-helpers.html (just a script tag loading "iron-test-helpers.js")
  - test-helpers.js
```

modulizer returns this:
```
- iron-test-helpers/
  D test-helpers.html
  M test-helpers.js (contains only the (now broken) imports from orig. html file)
```

**Comment by rictic** [comment]
We should at least crash in this case, and ideally pick an unclaimed filename.

**Comment by stramel** [comment]
@FredKSchott Am I missing something on the original post? Looking at `iron-test-helpers` it doesn't have a `iron-test-helpers.js` file already.

I'm able to see a handful of different ways this could be handled.

**Comment by justinfagnani** [comment]
@stramel the issue was other files in that repo, like test-helpers.html/test-helpers.js

**Comment by stramel** [comment]
@justinfagnani that was what I thought, thank you for clarifying and updating the original issue. 

I wonder if this could partially be handled by #182. Basically removing the wrapper.
