### ISSUE TITLE
Problem modulizing polymer/shop

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-modulizer#206]
`polymer/shop` has a lazy resources html import: https://github.com/Polymer/shop/blob/master/src/lazy-resources.html

When I ran `modulizer --out . --force` on `shop`, it did this: https://github.com/Polymer/shop/blob/8b7665099fe5094f39fe73ad825f5d00fc6471be/src/lazy-resources.html
- all the imports inside `lazy-resources` get converted to `script type=module`
- the file itself isn't renamed, and then you can't lazy import it with `import('./lazy-resources.html')` without a "wrong mimetype" warning

I think what should happen instead is this: https://github.com/Polymer/shop/blob/3.0/src/lazy-resources.js
- all the imports inside it get converted to `import foo` statements
- the file gets renamed to `lazy-resources.js`

/cc @frankiefu

**Comment by notwaldorf** [comment]
The same happened for https://github.com/Polymer/shop/blob/master/src/shop-list.html, which is a file that's only ever `importHref`ed. I thiiiiiink I expected modularizer to also look at all the `.html` files in the repo and do something with them, whether or not they're used.

**Comment by keanulee** [comment]
Related - element repos that have a "main" import (that imports all other files) are not converted to modules https://github.com/PolymerElements/app-layout/issues/526

**Comment by FredKSchott** [comment]
@notwaldorf this is a known issue, application modulization is not fully supported yet
@keanulee that issue has been fixed as of our last release

**Comment by e111077** [comment]
This seems to have been resolved already at some point. Modulizer is now producing:

```js
import './shop-icons.js';
import './shop-analytics.js';
import './shop-cart-data.js';
import './shop-cart-modal.js';
import './shop-snackbar.js';
import './shop-tabs.js';
import './shop-tab.js';
import './shop-network-warning.js';
import './shop-404-warning.js';
import './shop-cart-item.js';

/**
@license
Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
/* shop-app */
/* shop-list */
/* shop-detail */
/* shop-cart */
/* shop-checkout */
;
```

Ignore the missing deps that did not produce because of some unrelated modulizer issues.

**Comment by notwaldorf** [comment]
I ran master of `modulizer` on the master of `polymer-starter-kit`, and `my-app.js` still has all the wrong paths:
<img width="762" alt="screen shot 2018-04-04 at 4 42 02 pm" src="https://user-images.githubusercontent.com/1369170/38340225-21e7d7d0-3827-11e8-85d2-dd797f899ca9.png">

**Comment by notwaldorf** [comment]
(in your screenshot all those files are local dependencies. these get modulized fine. the problem is with 3rd parties, which don't have the right path from `node-modules`
