### ISSUE TITLE
Add wct-browser-legacy to devDependencies for elements with WCT-based tests

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-modulizer#208]
Add devDependency to `wct-browser-legacy` if elements have WCT-based tests.
   - Perhaps a simple heuristic for WCT based test would be if `web-component-tester` shows up anywhere in test files.

Also, will need to rewrite urls in test html files from:
   - `web-component-tester/browser.js` to `wct-browser-legacy/browser.js`
   - `web-component-tester/a11ySuite.js` to `wct-browser-legacy/a11ySuite.js`

Hopefully that's all that is needed to support WCT for npm.

**Comment by justinfagnani** [comment]
Related: #93

**Comment by stramel** [comment]
Related: #176

**Comment by stramel** [comment]
Seems like modulizer is currently handling dependency URL modifications by doing a look up in `dependency-map.json`. We currently have `web-component-tester` mapped to its npm package. If we instead switch that mapping to `wct-browser-legacy` npm package that corrects all the URLs mentioned above. However, this will mess up the output of the `devDependency` in `package.json`, as it is missing `web-component-tester`. 

I had asked @usergenic if it would really be necessary for elements to include `web-component-tester` if it already includes `wct-browser-legacy`, as generally `polymer-cli` handles running it. He wasn't sure how you guys wanted to handle this. 

Also, just to note, `wct-browser-legacy` seemed as though it had a significantly less complex flat install. I only ran into 3 conflicts.

**Comment by stramel** [comment]
I believe this can be closed now since #247 was merged #247 @FredKSchott
