### ISSUE TITLE
master build broken?

### ISSUE THREAD

**Issue by daKmoR** [Polymer/polymer-modulizer#212]
hey,

just clone and "npm i" gives typescript errors?
am I doing something wrong?
```
$ git clone https://github.com/Polymer/polymer-modulizer.git
$ cd polymer-modulizer
$ npm i
> polymer-modulizer@0.2.1 prepare /mnt/c/html/buildtest
> npm run build


> polymer-modulizer@0.2.1 build /mnt/c/html/buildtest
> tsc

node_modules/ix/asynciterable/fromevent.ts(31,19): error TS2339: Property 'addEventListener' does not exist on type 'EventTarget'.
node_modules/ix/asynciterable/fromevent.ts(31,43): error TS2304: Cannot find name 'EventListener'.
...
```

**Comment by stramel** [comment]
@daKmoR I was able to reproduce this with `npm i`.

However I believe the correct steps are:

1. `npm i -g yarn`
1. `git clone https://github.com/Polymer/polymer-modulizer.git`
1. `cd polymer-modulizer`
1. `yarn`


Results:
```sh
$ git clone https://github.com/Polymer/polymer-modulizer.git
Cloning into 'polymer-modulizer'...
remote: Counting objects: 1535, done.
remote: Total 1535 (delta 0), reused 0 (delta 0), pack-reused 1535
Receiving objects: 100% (1535/1535), 440.80 KiB | 559.00 KiB/s, done.
Resolving deltas: 100% (985/985), done.
Checking connectivity... done.
$ cd polymer-modulizer/
$ yarn
yarn install v1.2.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
$ npm run build
```
> polymer-modulizer@0.2.1 build /home/chrx/Projects/GitHub/test/polymer-modulizer
> tsc

Done in 19.30s.
```

**Comment by daKmoR** [comment]
ok but even in the Readme it says I should use `npm link`
https://github.com/Polymer/polymer-modulizer#running-on-polymer

and that fails as well right?

**Comment by stramel** [comment]
@daKmoR Correct, `npm link` fails. Although, it looks like you could use `yarn link` instead.

**Comment by daKmoR** [comment]
yarn link does not make it globally available... nor will you be able to use it on the command line...
(which would be needed here)

sure I can do all of this manually - but that is not very convenient...

**Comment by FredKSchott** [comment]
@daKmoR what about `yarn global add`? That should be == `npm link`.

**Comment by stramel** [comment]
@daKmoR the `yarn global add` worked for me :+1:
