### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-modulizer#236]

**Comment by stramel** [comment]
A good start might be to get tests running on appveyor?

**Comment by FredKSchott** [comment]
@stramel are we up and running on Windows? If tests are passing that should be a good sign

**Comment by stramel** [comment]
@fredkschott it looks like the build passed. I'm assuming that we are using your account? 

https://ci.appveyor.com/project/fredkschott/polymer-modulizer

It would be good to have a build badge on the readme

**Comment by FredKSchott** [comment]
Hmm, how did it get under my personal name? @justinfagnani do we have an official polymer account or are other repos under your name instead?

**Comment by justinfagnani** [comment]
@FredKSchott polymer-cli, etc., are under my personal account. I forget why it ended up that way, possibly because of the free plan. I think it's ok. If it's a problem we'll move all of them.

**Comment by stramel** [comment]
Lighthouse is currently under Paul Irish's account. So that seems to be the way you guys are handling it.
