### ISSUE TITLE
Update template conversion to use Polymer.html template tag

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-modulizer#239]
Assuming this proposal goes through: https://github.com/Polymer/polymer/issues/4937

We'll want to output:

```js
import {html, Element as PolymerElement} from '@polymer/polymer/polymer.js';

class MyElement extends PolymerElement {
  template = html`...`;
}
```

**Comment by kevinpschaaf** [comment]
@justinfagnani @FredKSchott Want to bump this up on the radar since https://github.com/Polymer/polymer/pull/4971 is about ready to land.  We'll likely make a `2.4-pre.1` pre-release and hold the feature until `modulizer` is updated with this change.
