### ISSUE TITLE
Favor default exports instead of named exports

### ISSUE THREAD

**Issue by MajorBreakfast** [Polymer/polymer-modulizer#243]
Currently named exports are used everywhere:
```JS
export const IronResizableBehavior = {
// ...
};
```
```JS
import { IronResizableBehavior } from '../iron-resizable-behavior/iron-resizable-behavior.js';
```

It would be much more idiomatic to use default exports in files that contain only one thing (and are named after that thing):
```JS
const IronResizableBehavior = {
// ...
};
export default IronResizableBehavior;
```
```JS
import IronResizableBehavior from '../iron-resizable-behavior/iron-resizable-behavior.js';
```
Advantages:
- Usage of `export default` the way it was intended to
- Users can easily rename the import without a complicated `as <other-name>` construct
- Node users like the single export pattern a lot (-> `module.exports = ...`)

**Comment by LarsDenBakker** [comment]
Names exports are better for static analysis, refactoring and tree shaking.

**Comment by MajorBreakfast** [comment]
@LarsDenBakker No. Default exports of ES6 module don't suffer from that problem. That problem exists only with CommonJS modules.

**Comment by MajorBreakfast** [comment]
Did you make any decisions about this?

Polymer is one of my favorite projects. I'd really like this to be done right before Polymer 3 launches. (Changing this at a later point is impossible without causing major code breakage in every package that depends on Polymer)

**Comment by KeithHenry** [comment]
Can't we do both?

```
export const IronResizableBehavior = {
// ...
};
export default IronResizableBehavior;
```

This would mean dynamic imports could use the exported name, while static imports could specify their own name for the default.

I don't think there is a cost to having both.

**Comment by MajorBreakfast** [comment]
@KeithHenry I think that's reasonable.

Though, for better code style the modulizer should IMO favor default imports (when other Polymer modules are imported). It's idiomatic JavaScript and also looks nicer.

**Comment by justinfagnani** [comment]
Default exports simply exports literally named `default`. Unless your module itself is implementing some kind of interface, where the importer _can't_ know ahead of time the name of thing to import, they don't actually add much value.

Since many of our modules have more than one thing to export, we would have to have a mix of default and named exports. I don't think this is something we want to pursue.

**Comment by MajorBreakfast** [comment]
> Default exports simply exports literally named default. [...] they don't actually add much value.

They do actually. Giving a new name is **a lot cleaner**.
Also it's idiomatic JavaScript.

> Since many of our modules have more than one thing to export, we would have to have a mix of default and named exports.

There is nothing wrong about mixing them. It's all about the file name:
`polymer-element.js` -> Default export `PolymerElement`
`easing-functions.js` -> Multiple named exports

**Comment by jsilvermist** [comment]
I agree, having default exports would be very convenient. @justinfagnani
