### ISSUE TITLE
Add wct flag support to modulizer CLI.

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-modulizer#291]
I want to run tests just on Chrome, for example, but I don't see a way to pass `-l chrome` to the wct invocation from the CLI.

**Comment by stramel** [comment]
Slightly related conversation, https://github.com/Polymer/polymer-modulizer/pull/271#discussion_r162261208

Brought up similarly how `paper-input` previously needed to run chrome and Firefox independently.

**Comment by FredKSchott** [comment]
Added in #386
