### ISSUE TITLE
Certain HTML files are being needlessly converted to modules

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer-modulizer#324]
Some HTML files have only a script inside of them and do not define elements. An example:

https://github.com/PolymerElements/app-layout/blob/master/app-scroll-effects/test/utils.html

This makes the function sameCSS visible to the [tests](https://github.com/PolymerElements/app-layout/blob/master/app-scroll-effects/test/parallax-background.html#L23), but if it is turned into a module then that function is not being exported.

Possible solutions:
1. Define this as a "wrapper"
2. find top-level functions and export them and import them
3. Fix this repo side and change it to `window.sameCSS = function (...`

**Comment by stramel** [comment]
Link to the converted version of the file above: https://github.com/PolymerElements/app-layout/blob/__auto_generated_3.0_preview/app-scroll-effects/test/utils.js

**Comment by e111077** [comment]
Spoke in private channel with justin and fred. Deemed that the most-appropriate approach is to go with solution 3

**Comment by FredKSchott** [comment]
For anyone from the future who finds this issue: As of right now this behavior is expected. A lone function defined in a script is treated as "private" (not a part of that file's external interface) unless it has the proper public jsdoc tags (`@function`/`@memberof` iirc).
