### ISSUE TITLE
Namespaces are being omitted

### ISSUE THREAD

**Issue by e111077** [Polymer/polymer-modulizer#345]
When a namespace is defined, it seems as if the modulizer is ignoring it. e.g.

```js
/**
 * @namespace
 * @memberof Polymer
 */
Polymer.MyNamespace {
  /**
   * @memberof Polymer.MyNamespace
   */
  myMethod() { return somFn.bind(this); }
}
```

is converted to
```js
export function myMethod() { return someFn.bind(Polymer.MyNamespace); }
// but Polymer is undefined and so is MyNamespace
```

see [PolymerElements/iron-overlay-behavior/iron-scroll-manager.html _lockScrollInteractions](https://github.com/PolymerElements/iron-overlay-behavior/blob/__auto_generated_3.0_preview/iron-scroll-manager.js#L162)

[before](https://github.com/PolymerElements/iron-overlay-behavior/blob/b7afaae994d527c8582d6ae8a2694e81c571e092/iron-scroll-manager.html#L224)

[after](https://github.com/PolymerElements/iron-overlay-behavior/blob/__auto_generated_3.0_preview/iron-scroll-manager.js#L164)

**Comment by justinfagnani** [comment]
This is a case that our `this` rewriting for namespaces isn't catching.

The specific lines being transformed incorrectly are:
- input: https://github.com/PolymerElements/paper-checkbox/blob/master/paper-checkbox.html#L239
- output: https://github.com/PolymerElements/iron-overlay-behavior/blob/__auto_generated_3.0_preview/iron-scroll-manager.js#L164

A simplified version is:

```js
Polymer.MyNamespace {
  methodA() {...}

  methodB() {
    return this.methodA.bind(this);
  }
}
```

I'd rather fix this by hand after conversion, but if the goal is to keep 2.x source as the source-of-truch, then we'll have to extend the heuristic to recognize `this.<function>.bind(this)` so we can output:

```js
export function methodA() {...}

export function methodB() {
  return methodA;
}
```

**Comment by justinfagnani** [comment]
cc @FredKSchott @kevinpschaaf and @graynorton 

I'm not sure how many more issues like this we have to get to 100% automation on our elements, but we're in the long tail for sure, IMO.

**Comment by e111077** [comment]
spoken offline, we also suggested fixing this issue by making modulizer substitute `undefined` for `this` when used in a function

**Comment by bicknellr** [comment]
Is this closable after #345 or is this different?
