### ISSUE TITLE
How should we convert references to web-component-tester?

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-modulizer#93]
Currently in https://github.com/Polymer/html2js/pull/91 I'm converting the wct bower module to the npm module of the same name, but we're probably going to want to do something more subtle if we want to break up the cli from the package that contains browser.js?

**Comment by stramel** [comment]
Should 3.0 elements be using `web-component-tester` or `wct-browser-legacy`? 

When I added `web-component-tester` to the element's `package.json` with `flat: true` there are tons of resolutions necessary. Whereas, `wct-browser-legacy`  only had a few resolutions. 

What is the recommended route for handling testing in 3.0?

**Comment by justinfagnani** [comment]
This is handled in the dependencies map.
